// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVWnP1Zh_TayOLfhQJf_QCXLFjLF_rFgI',
    appId: '1:1042805960588:web:9482c7134ff25c7518b0a9',
    messagingSenderId: '1042805960588',
    projectId: 'scoish-4325d',
    authDomain: 'scoish-4325d.firebaseapp.com',
    storageBucket: 'scoish-4325d.appspot.com',
    measurementId: 'G-40GHVMB6ZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClU-Bkg6PNYvR8VezzKHkQ3xDPQOFF9iw',
    appId: '1:1042805960588:android:435ebd0ea56d953c18b0a9',
    messagingSenderId: '1042805960588',
    projectId: 'scoish-4325d',
    storageBucket: 'scoish-4325d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACUHcRSAoU8rsoumkU3L3S43QHv5oHg4A',
    appId: '1:1042805960588:ios:a033209952f061ee18b0a9',
    messagingSenderId: '1042805960588',
    projectId: 'scoish-4325d',
    storageBucket: 'scoish-4325d.appspot.com',
    iosClientId: '1042805960588-ug55qcao0f9ag414dsie5djbhbm1m7on.apps.googleusercontent.com',
    iosBundleId: 'com.example.mezcal',
  );
}
